name = "library-webapp"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "LIBRARY_FILES"
bucket_name = "library-files"

[[d1_databases]]
binding = "DB"
database_name = "library-db"
database_id = "6282aef4-a953-4a08-af0a-de835a27abce"